services:
  php:
    build:
      context: ./php
    volumes:
      - ../:/var/www/html
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "7070:7070"

  nginx:
    image: nginx:alpine
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
